import { SessionOptions } from 'express-session';
import { ConnectionConfig } from 'mysql';
import * as mysql from "mysql";

export class Config {

    /**
     * This skeleton file works as a template.
     * Copy this file ill in the information in the mysqlOptions-object and save it as a typescript file: "config.ts"
     * Don't forget to compile it into JavaScript after saving. The name of the file should not be touched!
     * It is marked to be ignored by git since it is a system-specific configuration and should
     * not be overwritten by other team members.
     * You can remove this comment from the ts file afterwards.


*/
     //Verbindung zu Datenbank aufbauen
    public static mysqlOptions: ConnectionConfig = {

        database: "webp2",
        host: "localhost",
        user: "root",
};


    public static sessionOptions: SessionOptions = {
        cookie: {
            expires: new Date(Date.now() + (1000 * 60 * 60 * 3)), //1000ms*60ms+60ms * 3= 3h
        },
        name: 'connect.sid', // The name of the cookie generated by the server, e.g. 'connect.sid'
        rolling: true, // re-generate the cookie on every request
        saveUninitialized: true, // save session even if it stores no data
        resave: true,
        secret: Math.random().toString(), // add random encryption
    };

}